### ISSUE TITLE
Resolve SyntaxError: Unexpected end of JSON input while processing requests

### ISSUE THREAD

**Issue by Scorpibear** [Scorpibear/chegura#20]
info from log:

undefined:1
{"moves":["e4","c5","Nf3","d6","d4","Nc6","d5"
                                              

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/scorpibear/chegura/app/request-processor.js:34:23)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:387:10)
    at flow (_stream_readable.js:764:26)
    at resume_ (_stream_readable.js:744:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Scorpibear** [comment]
not valid for the latest versions
